name: ""
runbooks:
- name: bacckoff
  desc: runbooks for backoff
  selectors:
  - type: labelSelector
    selector: kubernetes.io/bootstrapping=rbac-defaults
  - type: jsonPathSelector
    selector: '{.apiVersion}=rbac.authorization.k8s.io/v1'
  - type: jsonPathSelector
    selector: '{.kind}=ClusterRole'
  - type: jsonPathSelector
    selector: '{.metadata.name}=cluster-admin'
  doc: backoff/pod-backoff.md
